version: "3.6"
services:
  postgres:
    image: postgis/postgis:12-master
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      # CUSTOM
      ACCOUNT_ACTION_URL: ${ACCOUNT_ACTION_URL}
      USERS_TRIGGER_URL: ${USERS_TRIGGER_URL}
      LEADS_TRIGGER_URL: ${LEADS_TRIGGER_URL}
      PROJECTS_TRIGGER_URL: ${PROJECTS_TRIGGER_URL}
      SEARCH_TRIGGER_URL: ${SEARCH_TRIGGER_URL}
      EVENT_SECRET: ${EVENT_SECRET}
      # DEV
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      # HASURA_GRAPHQL_WS_READ_COOKIE: "true"
      # HASURA_GRAPHQL_DISABLE_CORS: "true"
      # PROD
      # HASURA_GRAPHQL_ENABLED_APIS: "graphql"
      # HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      # HASURA_GRAPHQL_DEV_MODE: "false"
      # HASURA_GRAPHQL_CORS_DOMAIN: "https://nusszopf.org, https://dev-nusszopf.org"
      # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:
