version: "3.6"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.17.0
    restart: always
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    environment:
      MEILI_DB_PATH: "./data.ms"
      MEILI_HTTP_ADDR: "127.0.0.1:7700"
      MEILI_MASTER_KEY: meilipassword
      MEILI_NO_ANALYTICS: "true"
      MEILI_NO_SENTRY: "true"
      MEILI_ENV: "development"
