version: "3.6"
services:
  meilisearch:
    image: getmeili/meilisearch:v0.17.0
    restart: always
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    environment:
      MEILI_DB_PATH: "./data.ms"
      MEILI_MASTER_KEY: meilipassword
      MEILI_NO_ANALYTICS: "true"
      MEILI_NO_SENTRY: "true"
      MEILI_ENV: "development"
      # MEILI_HTTP_ADDR: "127.0.0.1:7700"
  cors:
    image: nginx:alpine
    environment:
      PROXY: meilisearch:7700
    ports:
      - 8000:80
    volumes:
      - ./nginx-cors-proxy.conf:/etc/nginx/conf.d/default.template:ro
    command:
      - /bin/sh
      - -c
      - envsubst '$$PROXY' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf &&
        exec nginx-debug -g 'daemon off;'
